### ISSUE TITLE
Cannot connect to an incoming call using only CRM initialized CCP app

### ISSUE THREAD

**Issue by sromocki** [aws/amazon-connect-streams#11]
Steps to reproduce:

1.) Initialize CCP app inside my application.
2.) Place a call to connect call queue.
3.) I can see the prompt to accept the incoming call, I press accept.
4.) Stays on "Connecting" for sometime and then eventually says "Missed Call".

Only way to accept the call that I found was to:
1.) Initialize CCP app inside my application.
2.) Open the CCP app inside Amazon Connect console.
3.) Place a call to connect call queue.
4.) I can see the prompt to accept the incoming call, I press accept.
5.) I'm able to connect to the call.

If the CCP app, that has the same ccpUrl that I initialize the ccp app with, is not open in another tab then I will not be able to accept the incoming call.

**Comment by pukhrajbal** [comment]
Per my experience - 
set softphone.allowFramedSoftphone: true during init.
also make sure there is no exception logged in console

**Comment by sromocki** [comment]
I'm confused by what allowFramedSoftphone is supposed to allow.

> allowFramedSoftphone: Normally, the softphone microphone and speaker components are not allowed to be hosted in an iframe. This is because the softphone must be hosted in a single window or tab. The window hosting the softphone session must not be closed during the course of a softphone call or the call will be disconnected. If allowFramedSoftphone is true, the softphone components will be allowed to be hosted in this window or tab.

I'm trying to load the CCP inside an iFrame in my application, so essentially it's and iFrame in an iFrame.  I'm not able to login or access my microphone if I use this approach.  If I open the application in a separate tab everything works fine.

**Comment by supelee** [comment]
Hi sromoki@,

Amazon Connect streams uses a SharedWorker behind the scenes to coordinate leader election for various different sets of activities, such as which frame/tab is responsible for ringtones and softphone connection management.  Normally, a CCP embedded in an iframe (via `initCCP( )`) is not eligible to participate in this leader election for softphone connection management.  With "allowFramedSoftphone", the CCP in the iframe is allowed to participate in leader election in this way.

The reason that this limitation exists is to prevent navigation on the parent page from dropping the softphone call, since it must be attached to an open tab/frame.  Some situations where using "allowedFrameSoftphone" makes sense include:

- Single page apps that the user will keep open for their entire usage session.
- CRM systems with PJAX style navigation that can support reloading page content without reloading the CCP iframe.

To address the signin issues above: The signin page is not allowed to be hosted in an iframe, this is why the CCP will launch a popup window with the login page if calling `initCCP( )` yields an empty iframe.  Make sure you allow popups from your Amazon Connect instance domain to keep this popup from being suppressed.

Thanks!

Lain

**Comment by sromocki** [comment]
@supelee OK thanks, I will use the login popup for now.  The original issue I described remains though.  I'm not able to accept a call unless I have "https://lily.us-east-1.amazonaws.com/connect/ccp#/" open in a separate tab.

**Comment by sromocki** [comment]
I downloaded the log for when the call is repeatedly not able to connect.

[agent-log-cannot-connect.txt](https://github.com/aws/amazon-connect-streams/files/1198486/agent-log-cannot-connect.txt)

**Comment by pukhrajbal** [comment]
Observing same thing - after closing popup window - call is not answered in the iframe.

**Comment by supelee** [comment]
sromocki@:

From the logs you attached, I think this is your culprit:

```
{
            "component": "softphone",
            "level": "ERROR",
            "text": " Softphone error occurred :  microphone_not_shared Your microphone is not enabled in your browser. ",
            "time": "2017-08-03T20:25:54.608Z",
            "exception": null,
            "objects": [],
            "line": 2
        }
```

This error indicates that the `getUserMedia( )` call failed as there is no microphone available to the browser.  This will prevent softphone from initializing and you won't be able to make or receive calls using softphone until this is remedied.

**Comment by sromocki** [comment]
Hmm, I've https://lily.us-east-1.amazonaws.com:443 to be allowed for microphone access in Chrome.  It only prompts me for access to the microphone outside of the iframe.  I allow it, but the app inside the iframe still does not have access.  I don't believe Chrome supports adding specific domain names to an exception list for microphone access so I'm a bit stuck.  @pukhrajbal Do you see the microphone access notification for the app inside the iframe?

![screen shot 2017-08-04 at 6 22 34 pm](https://user-images.githubusercontent.com/2022994/28990317-f1ac1f8a-7941-11e7-91c9-4880f08b81de.png)

**Comment by sromocki** [comment]
@supelee I found out why my microphone was being blocked.  It's because I'm using HTTP and a domain name other than just localhost for testing locally and getUserMedia only works with HTTPS.  I'm able to gives Chrome some command line args to workaround it:
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir=/tmp/chrome-tmp --unsafely-treat-insecure-origin-as-secure="http://myhost-localhost:3000"
```

However, now I'm seeing a different error related to running the app in an iframe:
Refused to display 'https://lily.us-east-1.amazonaws.com/connect/ccp#/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Currently researching how to get around this.

**Comment by HandyG52** [comment]
I was seeing this too - and it appears that until you authenticate via the
login page popup it will continue to print this in thr console.  If it
persists after you log in, then check to make sure you whitelisted your
origin domain on the connect admin page.

**Comment by sromocki** [comment]
@HandyG52 Yea, that was it.  I whitelisted my URL and everything works as expected now.  Thanks!
