### ISSUE TITLE
Connect Login with SAML

### ISSUE THREAD

**Issue by siddiq-syed** [aws/amazon-connect-streams#116]
Hi
I am using Amazon Connect with SAML.
https://docs.aws.amazon.com/connect/latest/adminguide/configure-saml.html

I was able to AssumeRoleWithSAML and retrieve the AWS credentials also I am able to interact and get the token.
https://docs.aws.amazon.com/connect/latest/APIReference/API_GetFederationToken.html

My scenario : I am invoking the ccp as below from a web-app., This is prompting me to enter the user-name pwd again is there a way to avoid the login and pass the credentials that has been obtained from the above step.  

 connect.core.initCCP(containerDiv, {
    ccpUrl: ccpUrl,
    loginPopup: true,
    loginUrl : loginUrl,
    softphone: {
    allowFramedSoftphone: true
    }
 });

I am trying to avoid the user entering username/pwd to  login to connect and instead pass some credentials to stream api to use the softphone.

**Comment by siddiq-syed** [comment]
Hello all.,

Anyone had this kinda issue ?

Did you guys implemented any alternate approach to avoid the extra login to the Connect in-order to use the softphone. ?

**Comment by mschersten** [comment]
You may want to look at issue [82](https://github.com/aws/amazon-connect-streams/issues/82).  It outlines how the loginUrl parameter came into being and might be what you need.

**Comment by jagadeeshaby** [comment]
As mentioned above please make use of the new login url parameter on initCCP to integrate with SAML use cases effectively. Code changes are already available on 1.3.2 version of streams. 

Please follow the https://github.com/aws/amazon-connect-streams/issues/82 for more detailed discussion on this topic. 

Hope that helps. Closing the issue here and Please feel free to reopen for further assistance.
