### ISSUE TITLE
initialConnection.isConnected() not available

### ISSUE THREAD

**Issue by clegeard** [aws/amazon-connect-streams#15]
[dialNumber.zip](https://github.com/aws/amazon-connect-streams/files/1217867/dialNumber.zip)
Hi,

I've created a button to call a particular number. 
This number can be directly called or it can also be called as a third party.
The first time I initialises the app, if I use this button it is working fine.
If I use this button to add a third party is working also fine, but if next I try to use this button to call directly without having another active connection, it is no longer working.
I get his error:

amazon-connect-v1.0.2.js:20450     Uncaught connect.StateError {}

I've checked that it is because for some reasons the function initialConnection.isConnected(); is not available, Although I can access the initialConnection object, I can't get any information from it.

I've attached my code

Thanks

**Comment by ninjamike54** [comment]
It looks like the variables that you're setting in your callback for connect.contact (c, initialConnection, initialActiveConnection, agentConn) are never being cleared, so once they're set (and therefore it looks like you have a third party call) they're never un-set. If you null them out, or otherwise reset them, before calling into connect.contact that should fix the issue.

**Comment by jagadeeshaby** [comment]
Hope the issue is fixed here. please feel free to reopen if it persists.
