### ISSUE TITLE
API to fetch Connect contact flow arn based on name

### ISSUE THREAD

**Issue by meghathakkar001** [aws/amazon-connect-streams#159]
Problem: 

We want to create modular self-service IVR where 1 connect flow represents an IVR Activity- e.g. Identification, Verification, Self-service Activity1(e.g. know my balance), Self-service Activity2 (e.g. make a payment) etc. Currently, connect contact flows do not provide any constructs like 'Invoke/Return' to pass control from one flow to another and return back to the same place from which it was invoked.

To overcome this limitation, we have implemented a call stack using AWS lambda with each stack element containing:
- state/position inside calling contact flow
**- Calling contact flow id: This can be used to return control from child contact flow.** We are planning to use 'Transfer to flow' module using this attribute.

**Connect Limitation:**
- 'Transfer to flow' requires ARN of the contact flow if passed as value of an attribute (dynamic). There is no direct API which takes flow name as input and gives ARN in the response.

**Change Required:**
- Allow attribute value as contact flow name instead of ARN in module "Transfer to flow"
OR
- Provide an API which takes contact flow name as input and provides ARN of the contact flow in the output
OR
- Provide current contact flow ARN as a system attribute
OR
- Provide contact flow ARN in the event being passed to lamda from AWS connect

**Comment by camstuart** [comment]
I would suggest maintaining a persisted list of ARN -> Name mappings of your contact flow.

You could populate this mapping by calling https://docs.aws.amazon.com/connect/latest/APIReference/API_ListContactFlows.html periodically 

You could then invoke a lambda function to look up a given flow ARN by flow name, and capture the response data into an attribute. Then use this captured attribute's variable in the transfer to flow block

The reason I suggest maintaining a mapping in a database, for example, is because Amazon Connect API calls attract a rate limit. So a database or cache mechanism would make sense here (or request a service limit increase, but you may not know how many calls you are going to need to make).

I hope that helps

**Comment by scoland** [comment]
Sorry to hear you're facing this limitation @meghathakkar001, and thanks for the helpful answer @camstuart.

I'm closing this issue as the answer provided is a workable solution and this board is meant for issues related specifically to the streams JS library.

In addition I'll pass the feature request along to the Contact Flow team for future consideration.
