### ISSUE TITLE
Get AgentId

### ISSUE THREAD

**Issue by markwinap** [aws/amazon-connect-streams#23]
I'm unable to get the ID of the agent that login. I noticed the ID is stored in cookies on the pop-up.
Can we add the AgentId on aget snapshot and contact snapshot.

Also if possible how to get the ID with current available functions

**Comment by efh365** [comment]
Currently you cannot get the agent id from the available functions. What is your use case for needing it?

**Comment by ninjamike54** [comment]
Yeah, we're aware of this gap and are working on a fix for it.

**Comment by mschersten** [comment]
Is the agent ID available anywhere in Connect, even when referencing variables within a contact flow?  For example, if I could set an attribute within the flow to something like, $.System.agentID, then I could pass it to the API that way.

I've even considered more radical ways like, once an agent has their first contact, using that contact ID to find the agent ID, and passing that back into my page.  But it looks like the agent ID isn't even stored anywhere in the logs.

**Comment by ninjamike54** [comment]
Clarifying question, in light of the comment "the ID is stored in cookies". Are you interested in the agent ID, or in the username?

**Comment by autrey** [comment]
I would vote for the login name since that would be unique. However, having both first and last name would be helpful (I know I can get first name today)

**Comment by markwinap** [comment]
Use cases are custom reporting. (I know that we have agent streams) custom agent screen interactions based on agent uid. I guess having both id uid is always a good option.

For example before agent streams I was reporting the agent status every minute (heartbeat) to notify if the agent closed the agent screen with logging out or changing his status to not ready etc.

**Comment by mschersten** [comment]
So we've been lax about how we refer to this, but there are two agent identifiers: ARN and Username (ie, the login name).  In the Kinesis CTR Firehose, these are Agent.ARN and Agent.Username.  This is my use case, so that I can pull CTRs to show the current agent their recent calls.  I would prefer to use the username, so that the agent ID is human-readable if I store it somewhere.

The way I'm working around this right now is to save the first contact ID after an agent logs in, then look up the agent username on the CTR for that contact, and then use that username to pull the rest of the CTRs.  This works fine so far, but I haven't tested it with transfers, and it takes a few minutes after the first contact.

**Comment by ninjamike54** [comment]
Got it, thanks. We were planning on exposing ARN, I'll make sure that when we do so we also expose the Username.

As an aside, the cookie referenced previously ("username") looks like it's the cookie used by the signin page to pre-fill the username. I'd recommend not building any dependencies on it for two reasons: it's not managed by Amazon Connect, so I can't guarantee it'll remain consistent, and since it's for the signin page in particular it likely won't be present for federated users (either administrative federation from the AWS console, or SAML SSO federation).

**Comment by mschersten** [comment]
Great, glad to see it.  Thanks, AWS team!

**Comment by markwinap** [comment]
Thanks all!

**Comment by vdineshmca** [comment]
Hi There,

Similarly, Is there any way to retrieve the Agent ARN through the Connect Stream?

Thanks,
Dinesh
