### ISSUE TITLE
AMAZON CONNECT ISSUE 

### ISSUE THREAD

**Issue by stupidasker** [aws/amazon-connect-streams#25]
REFUSED TO DISPLAY ..... IN A FRAME BECAUSE IT SET X-FRAME-OPTIONS TO SAMEORIGIN

ACK_TIMEOUT OCCURRED, ATTEMPTING TO POP THE LOGIN PAGE IF NOT ALREADY OPEN

OUR CONFIGURATION 👍 
<!DOCTYPE html> 
<html> 
<head> 
<title>Amazone Connect</title> 
</head> 
<body> 
<div id="containerDiv" ></div> 
</body> 
<script type="text/javascript" src="{{ asset('js/amazon-connect-v1.2.0.js') }}"></script> 
<script type="text/javascript"> 
connect.core.initCCP(containerDiv, { 
ccpUrl: 'https://INSTANCENAME.awsapps.com/connect/ccp#', 
loginPopup: true, 
softphone: { 
allowFramedSoftphone: true 
} 
}); 
</script> 
</html>

**Comment by sromocki** [comment]
You can try to increase the load timeout. I got mine at ccpLoadTimeout: 25000.
Also, have you whitelisted your development hostname in whatever instance your working with.

**Comment by sromocki** [comment]
Also, I use Amazon's login page in an iFrame and don't use the loginPopup since I think it's better for my users.  Maybe you desire the same functionality.   "loginPopup: false"

**Comment by sromocki** [comment]
Also, as a crappy workaround, you can use this chrome extension https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe?hl=en-US

**Comment by ninjamike54** [comment]
If you're seeing X-Frame-Options errors, the solution depends on what page in particular is throwing errors:

If the page is *.awsapps.com/connect/ccp, you'll need to whitelist your domain (see https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-instance.html#app-integration for details on how to do this)
If the page is *.awsapps/connect/login, this means that you aren't yet signed in (we don't support framing any page other than the CCP, including the login page), signing in with the login popup should fix the issue, since the integration automatically refreshes the frame.

**Comment by sfzhao99** [comment]
I got stung by this for a while, make sure your origin url is https if its not. Just something to double check

**Comment by alxx** [comment]
I'm using https, correctly provisioned in the Connect instance, I've tried both URLs (with /ccp and with /login), I've tried authenticating in the separate CCP, and nothing works. Whatever I do, I get "Refused to display '<URL>' in a frame because it set 'X-Frame-Options' to 'sameorigin'".

I understand that the iframe method is supposed to be phased out, but the latest version of the JS library still creates it.

Any suggestions?

**Comment by alxx** [comment]
After much googling I've found the problem: the correct URL should end in "/ccp#" with the pound making all the difference.
Why this isn't documented clearly, in bold red characters, is beyond me. I've been using the "/login" URL because that's the one I see in the Connect dashboard.

**Comment by anthonywebb** [comment]
Why allow loginPopup to be set to false if it literally does not work due to this cross domain issues.... SMH...  Cmon, fix it or remove it, but dont waste the developers time trying to debug it.

**Comment by jagadeeshaby** [comment]
Please feel free to reopen if the issue persists.

More details can be found here - https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-instance.html#app-integration

**Comment by ahmedyounis** [comment]
No where on
