### ISSUE TITLE
Does this sdk support all the regions or only us-east-1 ?

### ISSUE THREAD

**Issue by sekarsrra** [aws/amazon-connect-streams#28]
Does this sdk provide support for all the regions amazon connect instance or only us-east-1 ?
I am having the problem with eu-central-1 amazon connect instance. initccp() is not getting successful. Please let me know.

**Comment by efh365** [comment]
are you trying to use params.alias()? that is deprecated and only works with us-east-1.  if you specify the whole ccpUrl instead it should work for all supported regions. you may need to pass us-east-1 in because aws-configure requires a region but the region used in the ccpUrl will be ultimately respected.

**Comment by sekarsrra** [comment]
Thanks a lot for your response. Its working fine with the ccpURL :)
