### ISSUE TITLE
How to get the status of the agent

### ISSUE THREAD

**Issue by samurai8429** [aws/amazon-connect-streams#34]
hi
From the page different from ccp initializing page
How can I get agent information?

**Comment by ninjamike54** [comment]
There are a few ways to do this outside of the streams API - are you trying to get information about the currently authenticated user via the Streams API but outside of the website itself, or are you asking for ways to get agent status for agents within a Connect instance besides the user currently signed in?

**Comment by samurai8429** [comment]
Thank you for answering!!
>are you trying to get information about the currently authenticated user via the Streams API but >outside of the website itself
↑
I want to realize with this method

**Comment by ninjamike54** [comment]
If you want to know information about all agents within the same instance, we don't expose an API to do it currently (and when we do it'll be a different library/API than the streams library, considering that its purpose is real-time single-agent information). 

Until we expose an API to get this information, you can get this information manually by using the Real-Time Metrics (documented at https://docs.aws.amazon.com/connect/latest/userguide/real-time-metrics.html).

I'm going to close this issue, since this is likely to be a different API than Streams when it's released so it's out of scope of this repository; you can always open a support ticket via the AWS console to get help with features that're outside of this library.
